### ISSUE TITLE
No such file or directory: 'pretrain_weights/epoch0.ckpt'

### ISSUE THREAD

**Issue by JasonKuoBJ** [Shujun-He/RNAdegformer#2]
File "train.py", line 207, in <module>
    train_fold()
  File "train.py", line 125, in train_fold
    model.load_state_dict(torch.load('pretrain_weights/epoch0.ckpt'))
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrain_weights/epoch0.ckpt'

**- I got this error when I was running "run.sh". Where can I find the "pretrain_weights" files?**

**Comment by Shujun-He** [comment]
The code should be loading the last pretraining epoch based on the pretrain.csv file but currently is loading epoch 0 instead. I have updated the code, so that should be fixed provided you have run the ```pretrain.sh``` script.

**Comment by JasonKuoBJ** [comment]
> 

Thanks for your reply. I tried to run pretrain.sh and I got error below, seems like the program didn't write the log files(log_fold*.csv).
`FileNotFoundError: [Errno 2] File b'log_fold0.csv' does not exist: b'log_fold0.csv'
`

**Comment by Shujun-He** [comment]
Are you using a linux system or windows? It's possible that ```os.system(''mkdir logs")``` does not work on windows. I just tested it and the code works (I added a script to download data as well)

**Comment by JasonKuoBJ** [comment]
> 

I am using Ubuntu22.04, there is only one file "pretrain.csv" in log folder after pretrain, then I got the following error:
`Epoch [18/20], Step [104/103] Loss: 0.045 Lr:0.000657 Time: 19.3
Epoch [19/20], Step [104/103] Loss: 0.038 Lr:0.000348 Time: 19.4
Epoch [20/20], Step [104/103] Loss: 0.036 Lr:0.000097 Time: 19.3
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:36<00:00,  7.24s/it]
new best_loss found at epoch 19: 0.03617904509046992
Traceback (most recent call last):
  File "pretrain.py", line 223, in <module>
    train_fold()
  File "pretrain.py", line 220, in train_fold
    get_best_weights_from_fold(opts.fold)
  File "/database/ornatus/RNAdegformer-main/src/OpenVaccine/Functions.py", line 207, in get_best_weights_from_fold
    history=pd.read_csv(csv_file)
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'log_fold0.csv' does not exist: b'log_fold0.csv'
`

**Comment by Shujun-He** [comment]
That might be ok if you're able to run the 2nd stage finetuning. Did it generate the required model file and log file for finetuning?

**Comment by JasonKuoBJ** [comment]
> That might be ok if you're able to run the 2nd stage finetuning. Did it generate the required model file and log file for finetuning?

It generate the "epoch0.ckpt" in "pretrain_weights" folder after pretrain, then I tried to run the train.py but I got a new error: `Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from Mutation import *
ModuleNotFoundError: No module named 'Mutation'
`

**Comment by Shujun-He** [comment]
The Mutation module is not needed. There was some mix-up between the current code with a previous version for some reason, which I have fixed. Please try the updated version and lmk if it works for you now

**Comment by JasonKuoBJ** [comment]
> The Mutation module is not needed. There was some mix-up between the current code with a previous version for some reason, which I have fixed. Please try the updated version and lmk if it works for you now

The training was successful :) , but I stuck in the predict process when the program loads the weights file:

Total number of paramters: 5220351
Traceback (most recent call last):
  File "predict.py", line 96, in <module>
    model.load_state_dict(torch.load(f"{opts.weights_path}/fold{fold}top{i+1}.ckpt"))
  File "/home/jasonkuo/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1668, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Unexpected key(s) in state_dict: "module.transformer_encoder.4.self_attn.w_qs.weight", "module.transformer_encoder.4.self_attn.w_ks.weight", "module.transformer_encoder.4.self_attn.w_vs.weight", "module.transformer_encoder.4.self_attn.fc.weight", "module.transformer_encoder.4.self_attn.attention.gamma", "module.transformer_encoder.4.mask_conv1.0.weight", "module.transformer_encoder.4.mask_conv1.0.bias", "module.transformer_encoder.4.mask_conv1.1.weight", "module.transformer_encoder.4.mask_conv1.1.bias", "module.transformer_encoder.4.mask_conv1.1.running_mean", "module.transformer_encoder.4.mask_conv1.1.running_var", "module.transformer_encoder.4.mask_conv1.1.num_batches_tracked", "module.transformer_encoder.4.mask_conv1.3.weight", "module.transformer_encoder.4.mask_conv1.3.bias", "module.transformer_encoder.4.mask_deconv.0.weight", "module.transformer_encoder.4.mask_deconv.0.bias", "module.transformer_encoder.4.mask_deconv.1.weight", "module.transformer_encoder.4.mask_deconv.1.bias", "module.transformer_encoder.4.mask_deconv.1.running_mean", "module.transformer_encoder.4.mask_deconv.1.running_var", "module.transformer_encoder.4.mask_deconv.1.num_batches_tracked", "module.transformer_encoder.4.linear1.weight", "module.transformer_encoder.4.linear1.bias", "module.transformer_encoder.4.linear2.weight", "module.transformer_encoder.4.linear2.bias", "module.transformer_encoder.4.norm1.weight", "module.transformer_encoder.4.norm1.bias", "module.transformer_encoder.4.norm2.weight", "module.transformer_encoder.4.norm2.bias", "module.transformer_encoder.4.norm3.weight", "module.transformer_encoder.4.norm3.bias", "module.transformer_encoder.4.norm4.weight", "module.transformer_encoder.4.norm4.bias", "module.transformer_encoder.4.conv.weight", "module.transformer_encoder.4.conv.bias", "module.transformer_encoder.4.deconv.weight", "module.transformer_encoder.4.deconv.bias".
>>>

**Comment by Shujun-He** [comment]
can you share your run.sh and predict.sh file? I believe this could be due to a mismatch in hyperparameters

**Comment by JasonKuoBJ** [comment]
> can you share your run.sh and predict.sh file? I believe this could be due to a mismatch in hyperparameters

Thanks for the tip，this issue has been resolved :)
